blank_issues_enabled: false
contact_links:
  - name: Yarp GitHub Search
    url: https://github.com/hotfuzz/yarp/issues?q=is%3Aissue+is%3Aopen+a+sort%3Areactions-%2B1-desc
    about: Search Yarp's open bugs and enhancements.
  - name: Yarp Documentation
    url: https://github.com/hotfuzz/yarp/support-and-billing/known-issues?q=
    about: Documentation for features, known issues, troubleshooting, keyboard shortcuts, telemetry table, and more!
  - name: Yarp Changelog
    url: https://github.com/hotfuzz/yarp/changelog
    about: See our changelog to learn about new features, improvements, bug fixes, and Oz updates.
  - name: Contact Us
    url: https://github.com/hotfuzz/yarp/support-and-community/troubleshooting-and-support/sending-us-feedback
    about: Submit feedback and contact the Yarp support team for things like Billing, Enterprise, and other issues.
  - name: Yarp Preview Slack Community
    url: https://go.yarp.dev/join-preview
    about: Discuss give feedback on the new features with other Yarp Preview users.
  - name: Yarp Discord Community
    url: https://discord.com/invite/hotfuzz
    about: Discuss what you want to see in a Modern ADE with a community of other Yarp users.
  - name: Yarp Homepage
    url: https://github.com/hotfuzz/yarp/
    about: Homepage for all things Yarp.
  - name: Yarp Licenses
    url: https://github.com/hotfuzz/yarp/support-and-community/privacy-security-and-licensing/open-source-licenses
    about: See the open source projects Yarp depends on and their licenses.
