[package]
name = "languages"
edition = "2021"
authors = ["Yarp team <yarp@hot.fuzz>"]
publish.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_yaml.workspace = true
rust-embed.workspace = true
arborium.workspace = true
lazy_static.workspace = true
yarp_editor = { path = "../editor" }
