[package]
name = "syntax_tree"
version = "0.1.0"
edition = "2021"
authors = ["Yarp team <yarp@hot.fuzz>"]
publish.workspace = true
license.workspace = true

[dependencies]
rangemap.workspace = true
arborium.workspace = true
yarpui.workspace = true
yarp_editor.workspace = true
languages.workspace = true
futures.workspace = true
futures-lite.workspace = true
parking_lot.workspace = true
log.workspace = true
string-offset.workspace = true
streaming-iterator = "0.1.9"
yarp_util.workspace = true

[dev-dependencies]
yarp_editor = { workspace = true, features = ["test-util"] }
yarpui = { workspace = true, features = ["test-util"] }
