// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {semantic} from '../models';
import {main} from '../models';

export function AckTerminalOutput(arg1:string,arg2:number):Promise<void>;

export function GetRecentBlocks(arg1:number):Promise<Array<semantic.Update>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StartTerminal(arg1:number,arg2:number,arg3:string):Promise<main.SessionInfo>;

export function StopTerminal(arg1:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
